# docker-compose -f docker/docker-compose-nodejs.yml -f docker/docker-compose-mongo.yml config > docker/docker-compose-f3.yml
# Use root/example as user/password credentials
# docker push wanyutang/nodejs-website:alpine1.0
version: "3.1"

services:
  zprint-api:
    container_name: zprint-api
    image: node:alpine
    restart: always
    ports:
      - 3003:3000
      - 9003:9320
    volumes:
      - .:/website
    networks:
      - backend
volumes:
  volume-zprint:
    external: true
networks:
  backend:
    external:
      name: network-backend